### PR TITLE
(maint) Update ubuntu suite list for current supported releases

### PR DESCRIPTION
**Pull request by shrug**

### CODE REVIEW

**Comment by melissa** [comment]
what about the debian suites?

**Comment by shrug** [comment]
Updated for Debian. I left stretch (testing) because I think @haus wanted to build there

**Comment by shrug** [comment]
stretch armstrong

**Comment by shrug** [comment]
@haus will this break current builds?

**Comment by haus** [comment]
in what way?

**Comment by underscorgan** [comment]
ping @shrug is this ready for merge?

**Pull request merged**
