### PR TITLE
(maint) PC1 repos aren't available on stable or testing

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by haus** [comment]
@melissa I'd like to get this refactored in the future sometime. I think assuming PC1 or PC* will exist is probably bad. We already have the ability to set repos in project_data.yaml for packaging repo, we should use that or improve it if it is insufficient.

**Comment by haus** [comment]
Having said that, this is fine for a bugfix.

**Comment by melissa** [comment]
Oh, I forgot about that! You didn't mention that when this feature was first added...

**Comment by haus** [comment]
Yea, I don't think I weighed in on the other PR.

**Pull request merged**
